version: "3.9"

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  admin:
    build: .
    restart: always
    command: python -m admin.main
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
